# Generated by Django 5.1.1 on 2025-06-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='couple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.couple'),
        ),
    ]
