# Generated by Django 5.1.1 on 2025-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_activity_last_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('rejected', 'Rejected'), ('pool', 'Pool'), ('archived', 'Archived')], default='queued', max_length=20),
        ),
    ]
